name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - sigadefa # Триггер: запускать при пуше в ветку sigadefa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      # Установка MkDocs и Material Theme
      - run: pip install mkdocs mkdocs-material
      # Развертывание: команда без проблемной опции --base-url
      - run: mkdocs gh-deploy --force --remote-branch gh-pages

